language: swift

osx_image: xcode10.3

script:
  - xcodebuild -scheme YSLoaderSample -workspace YSLoaderSample.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.4' build test
  #- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace YSLoaderSample.xcworkspace -scheme YSLoaderSample -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
  #- sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)
